# YAML configuration file for the benchmarks


# Common parameters
batch_size: 32
epochs: 10
generation_limit: 50000
fitness_limit: 0.0
population_size: 100
transfer_learning: false
fitness_log_frequency: 1000
best_individual_save_frequency: 1000

# Genetic Algorithm parameters
ga:
  elite_size: 20
  learning_rate: 0.1
  crossover_rate: 0.2
  mutation_rate: 0.2

# African Vultures Optimization Algorithm parameters
avoa:
  L1: 0.8
  L2: 0.2
  w: 2.5
  P1: 0.6
  P2: 0.4
  P3: 0.6
  lb: -100
  ub: 100
  beta: 1.5

# Multi-Verse Optimizer parameters
mvo:
  min: 0.2
  max: 1.0
  p: 6.0
  lower_bound: -100
  upper_bound: 100

# Darts Game Optimizer parameters
dgo:
  throw_count: 3

# Sewing Training-Based Optimization parameters
stbo:
  lb: -100
  ub: 100
